# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0002_auto_20161122_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_player1', to='players.Player'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_player2', to='players.Player'),
        ),
    ]
