# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
        ('matchups', '0003_auto_20161202_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='season.Group'),
        ),
    ]
