# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('season', '0002_auto_20161206_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('map_name', models.CharField(max_length=30)),
                ('game_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_games', models.IntegerField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='season.Group')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_player1', to='players.Player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_player2', to='players.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='matchup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='season.Matchup'),
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_player1', to='players.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_player2', to='players.Player'),
        ),
    ]
