# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0003_auto_20161206_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupround',
            name='schedule_is_set',
            field=models.BooleanField(default=False),
        ),
    ]
