# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0004_groupround_schedule_is_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupround',
            name='schedule_is_set',
        ),
        migrations.AddField(
            model_name='group',
            name='schedule_is_set',
            field=models.BooleanField(default=False),
        ),
    ]
