# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0005_auto_20161206_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='map_name',
            field=models.CharField(default='TBD', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
