# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_name',
            field=models.CharField(default='I have no Discord name', max_length=30, verbose_name='Discord Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='bnet_id',
            field=models.IntegerField(verbose_name='Battle.net ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='bnet_name',
            field=models.CharField(max_length=30, verbose_name='Battle.net Username'),
        ),
        migrations.AlterField(
            model_name='player',
            name='bnet_profile_url',
            field=models.URLField(verbose_name='Battle.net Profile URL'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sc2_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='sc2_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
