# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 05:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20161220_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bnet_profile_url',
            field=models.URLField(validators=[django.core.validators.RegexValidator(code='Invalid URL', message="This doesn't appear to be a valid profile link.", regex='(http(s)?:\\/\\/)?[eu|na|kr]\\.battle.net\\/sc2\\/(en)\\/profile\\/\\d{6,7}\\/\\d\\/\\w+\\/$')], verbose_name='Battle.net Profile URL'),
        ),
    ]
