# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20161229_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='_total_matches',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
