# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_player__total_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='_total_matches',
        ),
    ]
