# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 04:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_remove_player__total_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='bnet_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bnet_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sc2_id',
        ),
        migrations.AlterField(
            model_name='player',
            name='bnet_profile_url',
            field=models.URLField(null=True, validators=[django.core.validators.RegexValidator(code='Invalid URL', message="This doesn't appear to be a valid profile link.", regex='^(http(s)?:\\/\\/)?(eu|us|kr)\\.battle.net\\/sc2\\/(en)\\/profile\\/\\d{6,7}\\/\\d\\/\\w+\\/$')], verbose_name='Battle.net Profile URL'),
        ),
        migrations.AlterField(
            model_name='player',
            name='discord_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Discord Username'),
        ),
        migrations.AlterField(
            model_name='player',
            name='race',
            field=models.CharField(choices=[('P', 'Protoss'), ('T', 'Terran'), ('Z', 'Zerg'), ('R', 'Random')], max_length=1, null=True),
        ),
    ]
